from django.urls import path

from . import views

urlpatterns = [
    path('none_httpstohttps_setup/<slug:test_id>/', views.none_httpstohttps_setup, name='referrerpolicy_none_httpstohttps_setup'),
    path('none_httptohttps_setup/<slug:test_id>/', views.none_httptohttps_setup, name='referrerpolicy_none_httptohttps_setup'),
    path('none_httpstohttp_setup/<slug:test_id>/', views.none_httpstohttp_setup, name='referrerpolicy_none_httpstohttp_setup'),
    path('none_httptohttp_setup/<slug:test_id>/', views.none_httptohttp_setup, name='referrerpolicy_none_httptohttp_setup'),
    path('none_httpstohttps_check/<slug:test_id>/', views.none_httpstohttps_check, name='referrerpolicy_none_httpstohttps_check'),
    path('none_httptohttps_check/<slug:test_id>/', views.none_httptohttps_check, name='referrerpolicy_none_httptohttps_check'),
    path('none_httpstohttp_check/<slug:test_id>/', views.none_httpstohttp_check, name='referrerpolicy_none_httpstohttp_check'),
    path('none_httptohttp_check/<slug:test_id>/', views.none_httptohttp_check, name='referrerpolicy_none_httptohttp_check'),
    path('noreferrer_setup/<slug:test_id>/', views.noreferrer_setup, name='referrerpolicy_noreferrer_setup'),
    path('noreferrer_check/<slug:test_id>/', views.noreferrer_check, name='referrerpolicy_noreferrer_check'),
    path('noreferrerwhendowngrade_httpstohttps_setup/<slug:test_id>/', views.noreferrerwhendowngrade_httpstohttps_setup, name='referrerpolicy_noreferrerwhendowngrade_httpstohttps_setup'),
    path('noreferrerwhendowngrade_httptohttps_setup/<slug:test_id>/', views.noreferrerwhendowngrade_httptohttps_setup, name='referrerpolicy_noreferrerwhendowngrade_httptohttps_setup'),
    path('noreferrerwhendowngrade_httpstohttp_setup/<slug:test_id>/', views.noreferrerwhendowngrade_httpstohttp_setup, name='referrerpolicy_noreferrerwhendowngrade_httpstohttp_setup'),
    path('noreferrerwhendowngrade_httptohttp_setup/<slug:test_id>/', views.noreferrerwhendowngrade_httptohttp_setup, name='referrerpolicy_noreferrerwhendowngrade_httptohttp_setup'),
    path('noreferrerwhendowngrade_httpstohttps_check/<slug:test_id>/', views.noreferrerwhendowngrade_httpstohttps_check, name='referrerpolicy_noreferrerwhendowngrade_httpstohttps_check'),
    path('noreferrerwhendowngrade_httptohttps_check/<slug:test_id>/', views.noreferrerwhendowngrade_httptohttps_check, name='referrerpolicy_noreferrerwhendowngrade_httptohttps_check'),
    path('noreferrerwhendowngrade_httpstohttp_check/<slug:test_id>/', views.noreferrerwhendowngrade_httpstohttp_check, name='referrerpolicy_noreferrerwhendowngrade_httpstohttp_check'),
    path('noreferrerwhendowngrade_httptohttp_check/<slug:test_id>/', views.noreferrerwhendowngrade_httptohttp_check, name='referrerpolicy_noreferrerwhendowngrade_httptohttp_check'),
    path('sameorigin_sameorigin_setup/<slug:test_id>/', views.sameorigin_sameorigin_setup, name='referrerpolicy_sameorigin_sameorigin_setup'),
    path('sameorigin_sameorigin_check/<slug:test_id>/', views.sameorigin_sameorigin_check, name='referrerpolicy_sameorigin_sameorigin_check'),    
    path('sameorigin_crossorigin_setup/<slug:test_id>/', views.sameorigin_crossorigin_setup, name='referrerpolicy_sameorigin_crossorigin_setup'),
    path('sameorigin_crossorigin_check/<slug:test_id>/', views.sameorigin_crossorigin_check, name='referrerpolicy_sameorigin_crossorigin_check'),
    path('origin_setup/<slug:test_id>/', views.origin_setup, name='referrerpolicy_origin_setup'),
    path('origin_check/<slug:test_id>/<slug:value>/', views.origin_check, name='referrerpolicy_origin_check'),
    path('strictorigin_httpstohttps_setup/<slug:test_id>/', views.strictorigin_httpstohttps_setup, name='referrerpolicy_strictorigin_httpstohttps_setup'),
    path('strictorigin_httptohttps_setup/<slug:test_id>/', views.strictorigin_httptohttps_setup, name='referrerpolicy_strictorigin_httptohttps_setup'),
    path('strictorigin_httpstohttp_setup/<slug:test_id>/', views.strictorigin_httpstohttp_setup, name='referrerpolicy_strictorigin_httpstohttp_setup'),
    path('strictorigin_httptohttp_setup/<slug:test_id>/', views.strictorigin_httptohttp_setup, name='referrerpolicy_strictorigin_httptohttp_setup'),
    path('strictorigin_httpstohttps_check/<slug:test_id>/', views.strictorigin_httpstohttps_check, name='referrerpolicy_strictorigin_httpstohttps_check'),
    path('strictorigin_httptohttps_check/<slug:test_id>/', views.strictorigin_httptohttps_check, name='referrerpolicy_strictorigin_httptohttps_check'),
    path('strictorigin_httpstohttp_check/<slug:test_id>/', views.strictorigin_httpstohttp_check, name='referrerpolicy_strictorigin_httpstohttp_check'),
    path('strictorigin_httptohttp_check/<slug:test_id>/', views.strictorigin_httptohttp_check, name='referrerpolicy_strictorigin_httptohttp_check'),
    path('originwhencrossorigin_sameorigin_setup/<slug:test_id>/', views.originwhencrossorigin_sameorigin_setup, name='referrerpolicy_originwhencrossorigin_sameorigin_setup'),
    path('originwhencrossorigin_sameorigin_check/<slug:test_id>/', views.originwhencrossorigin_sameorigin_check, name='referrerpolicy_originwhencrossorigin_sameorigin_check'),    
    path('originwhencrossorigin_crossorigin_setup/<slug:test_id>/', views.originwhencrossorigin_crossorigin_setup, name='referrerpolicy_originwhencrossorigin_crossorigin_setup'),
    path('originwhencrossorigin_crossorigin_check/<slug:test_id>/', views.originwhencrossorigin_crossorigin_check, name='referrerpolicy_originwhencrossorigin_crossorigin_check'),
    path('strictoriginwhencrossorigin_sameorigin_setup/<slug:test_id>/', views.strictoriginwhencrossorigin_sameorigin_setup, name='referrerpolicy_strictoriginwhencrossorigin_sameorigin_setup'),
    path('strictoriginwhencrossorigin_sameorigin_check/<slug:test_id>/', views.strictoriginwhencrossorigin_sameorigin_check, name='referrerpolicy_strictoriginwhencrossorigin_sameorigin_check'),    
    path('strictoriginwhencrossorigin_crossorigin_httptohttp_setup/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httptohttp_setup, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httptohttp_setup'),
    path('strictoriginwhencrossorigin_crossorigin_httptohttp_check/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httptohttp_check, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httptohttp_check'),
    path('strictoriginwhencrossorigin_crossorigin_httpstohttp_setup/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httpstohttp_setup, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httpstohttp_setup'),
    path('strictoriginwhencrossorigin_crossorigin_httpstohttp_check/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httpstohttp_check, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httpstohttp_check'),
    path('strictoriginwhencrossorigin_crossorigin_httptohttps_setup/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httptohttps_setup, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httptohttps_setup'),
    path('strictoriginwhencrossorigin_crossorigin_httptohttps_check/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httptohttps_check, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httptohttps_check'),
    path('strictoriginwhencrossorigin_crossorigin_httpstohttps_setup/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httpstohttps_setup, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httpstohttps_setup'),
    path('strictoriginwhencrossorigin_crossorigin_httpstohttps_check/<slug:test_id>/', views.strictoriginwhencrossorigin_crossorigin_httpstohttps_check, name='referrerpolicy_strictoriginwhencrossorigin_crossorigin_httpstohttps_check'),
    path('unsafeurl_sameorigin_setup/<slug:test_id>/', views.unsafeurl_sameorigin_setup, name='referrerpolicy_unsafeurl_sameorigin_setup'),
    path('unsafeurl_sameorigin_check/<slug:test_id>/', views.unsafeurl_sameorigin_check, name='referrerpolicy_unsafeurl_sameorigin_check'),    
    path('unsafeurl_crossorigin_httptohttp_setup/<slug:test_id>/', views.unsafeurl_crossorigin_httptohttp_setup, name='referrerpolicy_unsafeurl_crossorigin_httptohttp_setup'),
    path('unsafeurl_crossorigin_httptohttp_check/<slug:test_id>/', views.unsafeurl_crossorigin_httptohttp_check, name='referrerpolicy_unsafeurl_crossorigin_httptohttp_check'),
    path('unsafeurl_crossorigin_httpstohttp_setup/<slug:test_id>/', views.unsafeurl_crossorigin_httpstohttp_setup, name='referrerpolicy_unsafeurl_crossorigin_httpstohttp_setup'),
    path('unsafeurl_crossorigin_httpstohttp_check/<slug:test_id>/', views.unsafeurl_crossorigin_httpstohttp_check, name='referrerpolicy_unsafeurl_crossorigin_httpstohttp_check'),
    path('unsafeurl_crossorigin_httptohttps_setup/<slug:test_id>/', views.unsafeurl_crossorigin_httptohttps_setup, name='referrerpolicy_unsafeurl_crossorigin_httptohttps_setup'),
    path('unsafeurl_crossorigin_httptohttps_check/<slug:test_id>/', views.unsafeurl_crossorigin_httptohttps_check, name='referrerpolicy_unsafeurl_crossorigin_httptohttps_check'),
    path('unsafeurl_crossorigin_httpstohttps_setup/<slug:test_id>/', views.unsafeurl_crossorigin_httpstohttps_setup, name='referrerpolicy_unsafeurl_crossorigin_httpstohttps_setup'),
    path('unsafeurl_crossorigin_httpstohttps_check/<slug:test_id>/', views.unsafeurl_crossorigin_httpstohttps_check, name='referrerpolicy_unsafeurl_crossorigin_httpstohttps_check'),

    path('', views.index, name='index'),
]