# Generated by Django 2.2.4 on 2019-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserTestresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('test_date', models.DateTimeField()),
                ('user_agent', models.CharField(max_length=1000)),
                ('test1_passed', models.BooleanField(default=False)),
            ],
        ),
    ]
