# Generated by Django 2.2.4 on 2020-02-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browsertest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowserTestresult',
        ),
    ]
