import logging
from saveresult.models import TestResult
from analyzeresult.operators import OPERATOR_EQUALS
from analyzeresult.operators import OPERATOR_NOT_IN_RESULT
from contentsecuritypolicytest.testgroups_defaultsrc_imgsrc import TEST_DEFINITIONS_CSP_DEFAULTSRC_IMGSRC
from contentsecuritypolicytest.testgroups_defaultsrc_scriptsrc import TEST_DEFINITIONS_CSP_DEFAULTSRC_SCRIPTSRC
from contentsecuritypolicytest.testgroups_defaultsrc_stylesrc import TEST_DEFINITIONS_CSP_DEFAULTSRC_STYLESRC
from contentsecuritypolicytest.testgroups_defaultsrc_workersrc import TEST_DEFINITIONS_CSP_DEFAULTSRC_WORKERSRC
from contentsecuritypolicytest.testgroups_defaultsrc_framesrc import TEST_DEFINITIONS_CSP_DEFAULTSRC_FRAMESRC

TEST_DEFINITIONS_CSP_DEFAULTSRC = [] + TEST_DEFINITIONS_CSP_DEFAULTSRC_IMGSRC + TEST_DEFINITIONS_CSP_DEFAULTSRC_SCRIPTSRC + TEST_DEFINITIONS_CSP_DEFAULTSRC_FRAMESRC + TEST_DEFINITIONS_CSP_DEFAULTSRC_WORKERSRC + TEST_DEFINITIONS_CSP_DEFAULTSRC_STYLESRC