from django.urls import path

from . import views

urlpatterns = [
    path('framesrc_setup/<slug:test_id>/<slug:value>/', views.framesrc_setup, name='contentsecuritypolicytest.framesrc_setup'),
    path('framesrc_check/<slug:test_id>/<slug:value>/', views.framesrc_check, name='contentsecuritypolicytest.framesrc_check'),
    path('framesrc_frame/<slug:test_id>/<slug:value>/', views.framesrc_frame, name='contentsecuritypolicytest.framesrc_frame'),
    path('imgsrc_setup/<slug:test_id>/<slug:value>/', views.imgsrc_setup, name='contentsecuritypolicytest.imgsrc_setup'),
    path('imgsrc_check/<slug:test_id>/<slug:value>/', views.imgsrc_check, name='contentsecuritypolicytest.imgsrc_check'),
    path('scriptsrc_setup/<slug:test_id>/<slug:value>/', views.scriptsrc_setup, name='contentsecuritypolicytest.scriptsrc_setup'),
    path('scriptsrc_script/<slug:test_id>/<slug:value>/', views.scriptsrc_script, name='contentsecuritypolicytest.scriptsrc_script'),
    path('scriptsrc_unsafeeval_script/<slug:test_id>/<slug:value>/', views.scriptsrc_unsafeeval_script, name='contentsecuritypolicytest.scriptsrc_unsafeeval_script'),
    path('scriptsrc_strictdynamic_script/<slug:test_id>/<slug:value>/', views.scriptsrc_strictdynamic_script, name='contentsecuritypolicytest.scriptsrc_strictdynamic_script'),
    path('scriptsrc_strictdynamic_inserted_script/<slug:test_id>/<slug:value>/', views.scriptsrc_strictdynamic_inserted_script, name='contentsecuritypolicytest.scriptsrc_strictdynamic_inserted_script'),
    path('scriptsrc_check/<slug:test_id>/<slug:value>/', views.scriptsrc_check, name='contentsecuritypolicytest.scriptsrc_check'),
    path('frameancestors_setup/<slug:test_id>/<slug:value>/', views.frameancestors_setup, name='contentsecuritypolicytest.frameancestors_setup'),
    path('frameancestors_frame_outer/<slug:test_id>/<slug:value>/', views.frameancestors_frame_outer, name='contentsecuritypolicytest.frameancestors_frame_outer'),
    path('frameancestors_frame_inner/<slug:test_id>/<slug:value>/', views.frameancestors_frame_inner, name='contentsecuritypolicytest.frameancestors_frame_inner'),
    path('frameancestors_check/<slug:test_id>/<slug:value>/', views.frameancestors_check, name='contentsecuritypolicytest.frameancestors_check'),
    path('connectsrc_setup/<slug:test_id>/<slug:value>/', views.connectsrc_setup, name='contentsecuritypolicytest.connectsrc_setup'),
    path('connectsrc_check/<slug:test_id>/<slug:value>/', views.connectsrc_check, name='contentsecuritypolicytest.connectsrc_check'),
    path('defaultsrc_scriptsrc_setup/<slug:test_id>/<slug:value>/', views.defaultsrc_scriptsrc_setup, name='contentsecuritypolicytest.defaultsrc_scriptsrc_setup'),
    path('defaultsrc_framesrc_setup/<slug:test_id>/<slug:value>/', views.defaultsrc_framesrc_setup, name='contentsecuritypolicytest.defaultsrc_framesrc_setup'),
    path('defaultsrc_imgsrc_setup/<slug:test_id>/<slug:value>/', views.defaultsrc_imgsrc_setup, name='contentsecuritypolicytest.defaultsrc_imgsrc_setup'),
    path('defaultsrc_script/<slug:test_id>/<slug:value>/', views.defaultsrc_script, name='contentsecuritypolicytest.defaultsrc_script'),
    path('defaultsrc_unsafeeval_script/<slug:test_id>/<slug:value>/', views.defaultsrc_unsafeeval_script, name='contentsecuritypolicytest.defaultsrc_unsafeeval_script'),
    path('defaultsrc_strictdynamic_script/<slug:test_id>/<slug:value>/', views.defaultsrc_strictdynamic_script, name='contentsecuritypolicytest.defaultsrc_strictdynamic_script'),
    path('defaultsrc_strictdynamic_inserted_script/<slug:test_id>/<slug:value>/', views.defaultsrc_strictdynamic_inserted_script, name='contentsecuritypolicytest.defaultsrc_strictdynamic_inserted_script'),    
    path('defaultsrc_frame/<slug:test_id>/<slug:value>/', views.defaultsrc_frame, name='contentsecuritypolicytest.defaultsrc_frame'),
    path('defaultsrc_frame_outer/<slug:test_id>/<slug:value>/', views.defaultsrc_frame_outer, name='contentsecuritypolicytest.defaultsrc_frame_outer'),
    path('defaultsrc_frame_inner/<slug:test_id>/<slug:value>/', views.defaultsrc_frame_inner, name='contentsecuritypolicytest.defaultsrc_frame_inner'),
    path('defaultsrc_check/<slug:test_id>/<slug:value>/', views.defaultsrc_check, name='contentsecuritypolicytest.defaultsrc_check'),
    path('defaultsrc_stylesrc_setup/<slug:test_id>/<slug:value>/', views.defaultsrc_stylesrc_setup, name='contentsecuritypolicytest.defaultsrc_stylesrc_setup'),
    path('defaultsrc_stylesrc_stylesheet/<slug:test_id>/<slug:value>/<slug:element_id>/', views.defaultsrc_stylesrc_stylesheet, name='contentsecuritypolicytest.defaultsrc_stylesrc_stylesheet'),
    path('defaultsrc_workersrc_setup/<slug:test_id>/<slug:value>/', views.defaultsrc_workersrc_setup, name='contentsecuritypolicytest.defaultsrc_workersrc_setup'),
    path('defaultsrc_workersrc_script/<slug:test_id>/<slug:value>/', views.defaultsrc_workersrc_script, name='contentsecuritypolicytest.defaultsrc_workersrc_script'),
    path('defaultsrc_workersrc_check/<slug:test_id>/<slug:value>/', views.defaultsrc_workersrc_check, name='contentsecuritypolicytest.defaultsrc_workersrc_check'),
    path('workersrc_setup/<slug:test_id>/<slug:value>/', views.workersrc_setup, name='contentsecuritypolicytest.workersrc_setup'),
    path('workersrc_script/<slug:test_id>/<slug:value>/', views.workersrc_script, name='contentsecuritypolicytest.workersrc_script'),
    path('workersrc_check/<slug:test_id>/<slug:value>/', views.workersrc_check, name='contentsecuritypolicytest.workersrc_check'),
    path('stylesrc_setup/<slug:test_id>/<slug:value>/', views.stylesrc_setup, name='contentsecuritypolicytest.stylesrc_setup'),
    path('stylesrc_stylesheet/<slug:test_id>/<slug:value>/<slug:element_id>/', views.stylesrc_stylesheet, name='contentsecuritypolicytest.stylesrc_stylesheet'),
    path('stylesrc_check/<slug:test_id>/<slug:value>/', views.stylesrc_check, name='contentsecuritypolicytest.stylesrc_check'),
    path('', views.index, name='index'),
]