# Generated by Django 2.2.4 on 2020-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=1000)),
                ('result_key', models.CharField(max_length=1000)),
                ('result_value', models.CharField(max_length=1000)),
            ],
        ),
    ]
